### ISSUE TITLE
This hello world fails.

### ISSUE THREAD

**Issue by rdebath** [brunoczim/brainfree#1]
It does require wrapping cells, but that's fine for your interpreter.
``` bf
>-[>[-->]-<[-<]>]>>>>>>>>.>>>++.>..+++.[<]>>>>
----.>>>>>>---.>>.>---.<---.<-.<<<<<<<+.<<<+.
```

**Comment by brunoczim** [comment]
Thank you for reporting! I'll find out the problem

**Comment by brunoczim** [comment]
I forgot detecting nested loops! I believe now it is fixed.

**Comment by brunoczim** [comment]
Oh gosh. Another mistake I've made. But it's fixed.
